### PR TITLE
Travis build

### PR DESCRIPTION
**Pull request by robwhess**
Here's a first shot at a Travis build.  Let's see if it works.  Right now I have it set up so that PRs are built and tested.  A package will be published for every tagged commit on master.  I'm proposing that for releases, we use the "create a new release" feature on Github, which tags a build and generates tarballs, etc.  This, in turn will automatically trigger a Travis build that publishes the package and docs to PyPI.  If we do decide to go this route, I can add a check wherever the version is set in the source code to look for the version as the current git tag in an environment variable that Travis already provides.

The alternative would be to allow every commit into master to turn into a release.  I avoided that because I think it would require us to more tightly and manually manage version numbers, which would be a pain.

Let me know what you think.

TODO:
* [x] Decide on versioning mechanism.
* [x] If needed, set version in code to check for git tag in Travis environment variable.

/cc @huyng @pierreg @pumpikano

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by robwhess** [comment]
OK, @huyng @pumpikano @pierreg.  I think this is ready to go.  The PR ended up having a number of changes, but they fall into three classes:

1. A Travis build defined in `.travis.yml`.  I built for Python 2.7, 3.4, and 3.5, mainly because matplotlib (a dependency) doesn't install for other Pythons.  If we want to change this (e.g. by eliminating the matplotlib dependency), we can do it in a different PR.

2. Fixes to the code to get the build passing, mainly for Python 3.

3. Implementation of the versioning system I described above.  In particular, the release build will be triggered every time we tag the `master` branch, which I propose we do via Github's releases feature.  Everywhere in the code that the package's version is used (in `setup.py` and in `conf.py` for the docs build), I check to see if the `TRAVIS_TAG` environment variable is available.  This will hold the name of the git tag in a travis build.  If that environment variable is not available, it just uses a default version (right now 1.0).  This means that when we tag `master`, we should tag it with a proper version number, e.g. '1.0.2' or 'v1.0.2' (either form will be correctly parsed).  We can also do release candidate builds with tags like this: '1.1rc1' or '1.1-rc1' or 'v1.1rc1' or 'v1.1-rc1' (these will all be parsed correctly).  Every time we tag a version like this, it'll be built and automatically published to PyPI.

Let me know what you think.

**Comment by pumpikano** [comment]
I think this set up is great! 👍 

Is matplotlib a dependence? - I don't see it in setup.py, but I do see pydot. In any case, this is just for plotting the graph, right? I think we should have this as an optional dependency in that case.

**Comment by robwhess** [comment]
I added matplotlib as a dependency (in `setup.py`---it was already a dependency in the code) in this PR: https://github.com/yahoo/graphkit/pull/3/files#diff-2eeaed663bd0d25b7e608891384b7298R30.  But yeah, it is only for the plotting stuff.  I agree that we should add this as an optional dependency, but that's beyond the scope of this PR.

**Comment by robwhess** [comment]
I'm going to tag a v1.0 release and see if this baby works!

**Pull request merged**
