### PR TITLE
Add optional() modifier

### PR DESCRIPTION
**Pull request by robwhess**
This PR adds the `optional()` modifier for values in `needs`.  This lets some input values be designated as optional like so:
```python
from graphkit import operation, compose
from graphkit.modifiers import optional

def myadd(a, b, c=0):
    return a + b + c

graph = compose('mygraph')(
    operator(name='myadd', needs=['a', 'b', optional('c')], provides='sum')(myadd)
)

# Gives {'sum': 7}.
graph({'a': 5, 'b': 2})

# Gives {'sum': 11}.
graph({'a': 5, 'b': 2, 'c': 4})
```

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by robwhess** [comment]
I also added some cleanup.  There's not actually a travis build defined yet, so we can ignore that failure.

**Comment by huyng** [comment]
👍

**Comment by huyng** [comment]
congrats on the first opensource PR merged into graphkit!

**Pull request merged**
