### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by robwhess**
This PR updates docs in preparation for publication via Travis build.

/cc @huyng @pierreg @pumpikano

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by robwhess** [comment]
Travis build will fail because we don't actually have a build defined yet, so the failure is OK for merging purposes.

**Comment by robwhess** [comment]
You can look at the new docs like this:
```
pip install sphinx sphinx_rtd_theme
cd docs/
make html
```
The docs will be built in `docs/build/`.

**Comment by pumpikano** [comment]
Starting from a clean virtualenv, I see the following:

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.5
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.

Extension error:
sphinx.ext.mathjax: other math package is already loaded
make: *** [html] Error 1
```

Any ideas?

**Comment by robwhess** [comment]
@pumpikano, are you sure you checked out the PR?  I specifically changed these lines to fix that warning and error:

https://github.com/yahoo/graphkit/pull/2/files#diff-1ec61223727a10e5e4c74c68336809fcL38

**Comment by pumpikano** [comment]
Oooops must have been too late for my brain 😊  . Looks fantastic! 👍

**Pull request merged**
